apps/analysis/api/urls.py
from django.conf.urls import url
from core.api.routers import PostHackedRouter
from . import views

router = PostHackedRouter()
router.include_root_view = False

# reverse('api:word-list'), reverse('api:word-detail', kwargs={'pk': 1})
router.register(r'word', views.WordViewSet, base_name='word')
router.register(r'skintype', views.SkinTypeViewSet, base_name='skintype')

urlpatterns = [
    url(r'^word/autocomplete/$', views.WordAutocompleteAPIView.as_view(), name='word-autocomplete'),
]

urlpatterns += router.urls

apps/analysis/urls.py
from django.conf.urls import url
from . import views

# urls for word
urlpatterns = [
    url(r'^word/add/$', views.WordAddView.as_view(), name='word-add'),
    url(r'^word/list/$', views.WordListView.as_view(), name='word-list'),
    url(r'^word/(?P<pk>\d+)/$', views.WordDetailView.as_view(), name='word-detail'),
    url(r'^word/(?P<pk>\d+)/edit/$', views.WordUpdateView.as_view(), name='word-update'),

    url(r'^skintype/add/$', views.SkinTypeAddView.as_view(), name='skintype-add'),
    url(r'^skintype/list/$', views.SkinTypeListView.as_view(), name='skintype-list'),
    url(r'^skintype/(?P<pk>\d+)/$', views.SkinTypeDetailView.as_view(), name='skintype-detail'),
    url(r'^skintype/(?P<pk>\d+)/edit/$', views.SkinTypeUpdateView.as_view(), name='skintype-update'),
]

config/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.views import serve

# from wagtail.wagtailadmin import urls as wagtailadmin_urls
# from wagtail.wagtailcore import urls as wagtail_urls
# from wagtail.wagtaildocs import urls as wagtaildocs_urls
# from wagtail.wagtailimages import urls as wagtailimages_urls
# from apps.wagtail.search.views import search as wagtail_search

from core.auth_user.views import ChangePasswordView
from core import auth_user
from core.auth_user.forms import CustomPasswordResetForm, CustomSetPasswordForm


def if_installed(appname, *args, **kwargs):
    ret = url(*args, **kwargs)
    if appname not in settings.INSTALLED_APPS:
        ret.resolve = lambda *args: None
    return ret


wagtail_urlpatterns = [
    # url(r'^admin/', include(wagtailadmin_urls)),
    # url(r'^documents/', include(wagtaildocs_urls)),
    # url(r'^images/', include(wagtailimages_urls)),
    # url(r'^search/$', wagtail_search, name='wagtail_search'),
    # url(r'^pages/', include(wagtail_urls)),
]

apps_urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('apps.dashboard.urls', namespace='dashboard')),
    url(r'^', include('core.auth_user.urls', namespace='users')),
    url(r'^brand/', include('apps.brand.urls', namespace='brand')),
    url(r'^product/', include('apps.product.urls', namespace='product')),
    url(r'^premium_product/', include('apps.premium_product.urls', namespace='premium_product')),
    url(r'^analysis/', include('apps.analysis.urls', namespace='analysis')),
    url(r'^survey/', include('apps.survey.urls', namespace='survey')),
    url(r'^report/', include('apps.report.urls', namespace='report')),
    url(r'^wx/', include('apps.weixin.urls', namespace='weixin')),
]

# REST API
api_urlpatterns = [
    url(r'^wx/', include('apps.weixin.api.urls')),
    url(r'^brand/', include('apps.brand.api.urls')),
    url(r'^product/', include('apps.product.api.urls')),
    url(r'^premium_product/', include('apps.premium_product.api.urls')),
    url(r'^analysis/', include('apps.analysis.api.urls')),
    url(r'^survey/', include('apps.survey.api.urls')),
    url(r'^report/', include('apps.report.api.urls')),
]

urlpatterns = wagtail_urlpatterns + apps_urlpatterns + [
    # REST API
    url(r'^api/', include(api_urlpatterns, namespace='api')),

    # auth
    url('^auth/change-password/$', ChangePasswordView.as_view(), name='change_password'),
    url('^auth/change-password-done/$', auth_user.views.ChangePasswordDoneView.as_view(), name='password_change_done'),

    # password reset
    url(r'^password/reset/$', auth_views.password_reset, {'template_name': 'adminlte/password_reset_form.html',
                                                          'email_template_name': 'adminlte/password_reset_email.html',
                                                          'password_reset_form': CustomPasswordResetForm},
        name='password_reset'),
    url(r'^password/reset/done/$', auth_views.password_reset_done,
        {'template_name': 'adminlte/password_reset_done.html'},
        name='password_reset_done'),
    url(r'^password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', auth_views.password_reset_confirm,
        {'template_name': 'adminlte/password_reset_confirm.html',
         'set_password_form': CustomSetPasswordForm},
        name='password_reset_confirm'),
    url(r'^password/reset/complete/$', auth_views.password_reset_complete,
        {'template_name': 'adminlte/password_reset_complete.html'},
        name='password_reset_complete'),

    # dbsettings
    # url(r'^djadmin/settings/', include('dbsettings.urls')),

    # django-tinymce
    # url(r'^tinymce/', include('tinymce.urls')),

    url(r'^MP_verify_aVcytWJVmPok60D5\.txt$', serve, kwargs={'path': 'MP_verify_aVcytWJVmPok60D5.txt'}),

    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:
    # url(r'^home/', include(wagtail_urls)),
]

if settings.DEBUG:
    from rest_framework_swagger.views import get_swagger_view
    from django.conf.urls.static import static

    urlpatterns += [
        url(r'^api/docs/$', get_swagger_view(title='OZSales API'))
    ]

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/analysis/models.py
# coding=utf-8
from django.db import models
from django.utils.translation import ugettext_lazy as _
from pypinyin import Style
from config.constants import (SKIN_OILY_TYPE_CHOICES, SKIN_SENSITIVE_TYPE_CHOICES, SKIN_PIGMENT_TYPE_CHOICES,
                              SKIN_LOOSE_TYPE_CHOICES, PURPOSE_CHOICES, SKIN_TYPE_DIMENSION_CHOICES)
from core.django.models import PinYinFieldModelMixin


class SkinType(models.Model):
    dimension = models.CharField(_('维度'), max_length=64, choices=SKIN_TYPE_DIMENSION_CHOICES, blank=True)
    name = models.CharField(_('名称'), max_length=64,
                            choices=SKIN_OILY_TYPE_CHOICES + SKIN_SENSITIVE_TYPE_CHOICES + SKIN_PIGMENT_TYPE_CHOICES + SKIN_LOOSE_TYPE_CHOICES,
                            blank=True)
    short_name = models.CharField(_('简称'), max_length=64, blank=True)
    lower_bound = models.IntegerField(_('分数下界'), blank=True, null=True)
    upper_bound = models.IntegerField(_('分数上界'), blank=True, null=True)
    short_description = models.TextField(_('简评'), max_length=512, blank=True)
    description = models.TextField(_('备注'), blank=True)

    def __str__(self):
        return self.name

    class Meta:
        unique_together = ("dimension", "name")

    @staticmethod
    def get_oily_type(score):
        if score:
            for t in SkinType.objects.filter(dimension='油性or干性'):
                if t.lower_bound <= score <= t.upper_bound:
                    return t
        return None

    @staticmethod
    def get_sensitive_type(score):
        if score:
            for t in SkinType.objects.filter(dimension='敏感or耐受'):
                if t.lower_bound <= score <= t.upper_bound:
                    return t
        return None

    @staticmethod
    def get_pigment_type(score):
        if score:
            for t in SkinType.objects.filter(dimension='色素or非色素'):
                if t.lower_bound <= score <= t.upper_bound:
                    return t
        return None

    @staticmethod
    def get_loose_type(score):
        if score:
            for t in SkinType.objects.filter(dimension='易皱纹or紧致'):
                if t.lower_bound <= score <= t.upper_bound:
                    return t
        return None


class Word(PinYinFieldModelMixin, models.Model):
    """肤质对应话术, skin_word"""
    purpose = models.CharField(_('目标'), max_length=64, choices=PURPOSE_CHOICES, blank=True)  # 问卷目标
    oily_type = models.ForeignKey('analysis.SkinType', verbose_name=_('油性or干性'), blank=True, null=True,
                                  related_name='word_oily_type')
    sensitive_type = models.ForeignKey('analysis.SkinType', verbose_name=_('敏感or耐受'), blank=True, null=True,
                                       related_name='word_sensitive_type')
    pigment_type = models.ForeignKey('analysis.SkinType', verbose_name=_('色素or非色素'), blank=True, null=True,
                                     related_name='word_pigment_type')
    loose_type = models.ForeignKey('analysis.SkinType', verbose_name=_('易皱纹or紧致'), blank=True, null=True,
                                   related_name='word_loose_type')

    report = models.TextField(_('皮肤检测报告总结'), blank=True)  # 总结报告，填充值问卷报告的总结
    problem = models.TextField(_('我们认为您存在的问题'), blank=True)  # 存在的问题
    avoid_component = models.TextField(_('需要避免使用的皮肤护理成分'), blank=True)  # 避免使用的成分
    doctor_advice = models.TextField(_('听听皮肤科医生怎么说'), blank=True)  # 医生建议
    emergency_solution = models.TextField(_('应急方案'), blank=True)  # 应急方案
    maintain_solution = models.TextField(_('日常维稳方案'), blank=True)  # 维稳方案

    day_instruct = models.TextField(_('日间'), blank=True)  # 日间指导
    night_instruct = models.TextField(_('夜间'), blank=True)  # 夜间指导
    mask_instruct = models.TextField(_('面膜'), blank=True)  # 面膜指导

    pinyin = models.CharField(_(u'pinyin'), max_length=1024, blank=True)
    pinyin_fields_conf = [
        ('purpose', Style.NORMAL, False),
        ('oily_type__name', Style.NORMAL, False),
        ('sensitive_type__name', Style.NORMAL, False),
        ('pigment_type__name', Style.NORMAL, False),
        ('loose_type__name', Style.NORMAL, False),
    ]

    class Meta:
        verbose_name_plural = _('话术')
        verbose_name = _('话术')
        unique_together = (('purpose', 'oily_type', 'sensitive_type', 'pigment_type', 'loose_type'),)

    def __str__(self):
        return '%s-%s_%s_%s_%s' % (
        self.purpose, self.oily_type, self.sensitive_type, self.pigment_type, self.loose_type)

apps/analysis/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from .models import Word, SkinType


class WordAddForm(forms.ModelForm):
    class Meta:
        model = Word
        exclude = ['pinyin']

    def __init__(self, *args, **kwargs):
        super(WordAddForm, self).__init__(*args, **kwargs)
        self.fields['oily_type'].queryset = SkinType.objects.filter(dimension='油性or干性')
        self.fields['sensitive_type'].queryset = SkinType.objects.filter(dimension='敏感or耐受')
        self.fields['pigment_type'].queryset = SkinType.objects.filter(dimension='色素or非色素')
        self.fields['loose_type'].queryset = SkinType.objects.filter(dimension='易皱纹or紧致')


class WordUpdateForm(WordAddForm):
    class Meta:
        model = Word
        exclude = ['pinyin']


class WordDetailForm(WordAddForm):
    class Meta:
        model = Word
        exclude = ['pinyin']


class SkinTypeAddForm(forms.ModelForm):
    class Meta:
        model = SkinType
        fields = '__all__'


class SkinTypeUpdateForm(forms.ModelForm):
    class Meta:
        model = SkinType
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(SkinTypeUpdateForm, self).__init__(*args, **kwargs)
        self.fields['name'].disabled = True
        self.fields['name'].widget.attrs['readonly'] = True
        self.fields['dimension'].disabled = True
        self.fields['dimension'].widget.attrs['readonly'] = True

class SkinTypeDetailForm(forms.ModelForm):
    class Meta:
        model = SkinType
        fields = '__all__'

apps/analysis/api/views.py
import logging

from braces.views import SuperuserRequiredMixin
from dal import autocomplete
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework import filters

from core.api.filters import PinyinSearchFilter
from core.api.permission import AdminOnlyPermissions
from core.django.autocomplete import HansSelect2ViewMixin
from core.api.views import CommonViewSet
from ..models import Word, SkinType
from . import serializers

log = logging.getLogger(__name__)


class WordViewSet(CommonViewSet):
    """ API views for Word """
    queryset = Word.objects.all()
    serializer_class = serializers.WordSerializer
    filter_fields = ['purpose', 'oily_type__name', 'sensitive_type__name', 'pigment_type__name', 'loose_type__name']
    search_fields = ['purpose', 'oily_type__name', 'sensitive_type__name', 'pigment_type__name', 'loose_type__name']
    permission_classes = (AdminOnlyPermissions,)
    pinyin_search_fields = ['pinyin']  # search only input are all ascii chars
    filter_backends = (DjangoFilterBackend,
                       PinyinSearchFilter,
                       filters.OrderingFilter)


class SkinTypeViewSet(CommonViewSet):
    """ API views for Word """
    queryset = SkinType.objects.all()
    serializer_class = serializers.SkinTypeSerializer
    filter_fields = ['name', 'short_name']
    search_fields = ['name',]
    permission_classes = (AdminOnlyPermissions,)

class WordAutocompleteAPIView(SuperuserRequiredMixin, HansSelect2ViewMixin, autocomplete.Select2QuerySetView):
    model = Word
    paginate_by = 20

apps/analysis/views.py
from django.views.generic import ListView, CreateView, UpdateView
from braces.views import SuperuserRequiredMixin

from core.django.views import CommonContextMixin
from .models import Word, SkinType
from . import forms


class WordListView(SuperuserRequiredMixin, CommonContextMixin, ListView):
    """ List views for Word """
    model = Word
    template_name = 'analysis/word_list.html'

    def get_context_data(self, **kwargs):
        context = super(WordListView, self).get_context_data(**kwargs)
        context['table_titles'] = [u'目标', u'油性or干性', u'敏感or耐受', u'色素or非色素', u'易皱or紧致', '']
        context['table_fields'] = ['purpose', 'oily_type_display', 'sensitive_type_display', 'pigment_type_display',
                                   'loose_type_display', 'id']
        return context


class WordAddView(SuperuserRequiredMixin, CommonContextMixin, CreateView):
    """ Add views for Word """
    model = Word
    form_class = forms.WordAddForm
    template_name = 'analysis/word_form.html'


class WordUpdateView(SuperuserRequiredMixin, CommonContextMixin, UpdateView):
    """ Update views for Word """
    model = Word
    form_class = forms.WordUpdateForm
    template_name = 'analysis/word_form.html'


class WordDetailView(SuperuserRequiredMixin, CommonContextMixin, UpdateView):
    """ Detail views for Word """
    model = Word
    form_class = forms.WordDetailForm
    template_name = 'adminlte/common_detail.html'


class SkinTypeListView(SuperuserRequiredMixin, CommonContextMixin, ListView):
    """ List views for SkinType """
    model = SkinType
    template_name = 'analysis/skintype_list.html'

    def get_context_data(self, **kwargs):
        context = super(SkinTypeListView, self).get_context_data(**kwargs)
        context['table_titles'] = [u'维度', u'名称', '分数下界', '分数上界', u'简称', u'备注', '']
        context['table_fields'] = ['dimension', 'name', 'lower_bound', 'upper_bound', 'short_name', 'description', 'id']
        return context


class SkinTypeAddView(SuperuserRequiredMixin, CommonContextMixin, CreateView):
    """ Add views for SkinType """
    model = SkinType
    form_class = forms.SkinTypeAddForm
    template_name = 'analysis/skintype_form.html'


class SkinTypeUpdateView(SuperuserRequiredMixin, CommonContextMixin, UpdateView):
    """ Update views for SkinType """
    model = SkinType
    form_class = forms.SkinTypeUpdateForm
    template_name = 'analysis/skintype_form.html'


class SkinTypeDetailView(SuperuserRequiredMixin, CommonContextMixin, UpdateView):
    """ Detail views for SkinType """
    model = SkinType
    form_class = forms.SkinTypeDetailForm
    template_name = 'adminlte/common_detail.html'

apps/analysis/templates/analysis/_menu.html
<li class="treeview active">
    <a href="javascript:void(0)">
        <i class='fa fa-shopping-bag'></i>
        <b>分析</b>
    </a>

    <ul class="treeview-menu menu-open" style="display: block;">
        <li>
            <a href="{% url 'analysis:skintype-list' %}" class="main">
                <i class="fa fa-circle-o"></i>
                肤质类型
            </a>
        </li>
        <li>
            <a href="{% url 'analysis:word-add' %}" class="pull-right"><i class="fa fa-plus" aria-hidden="true"></i></a>
            <a href="{% url 'analysis:word-list' %}" class="main">
                <i class="fa fa-circle-o"></i>
                话术
            </a>
        </li>
    </ul>
</li>

apps/analysis/templates/analysis/skintype_form.html
{% extends "adminlte/common_form.html" %}
{% load static adminlte_tags %}

{% block form_content %}
    <div class="col-xs-12">
    {% for field in form %}
        <div class="form-group {% if field.errors %}error{% endif %} {% if field.is_hidden %}hide{% endif %}">
            <label for="id_{{ field.name }}" class="col-sm-2 col-xs-3 control-label">{{ field.label }}</label>
            <div class="col-sm-6 col-xs-9">
                {{ field }}
            </div>
            {% if field.errors %}
                <div class="col-sm-4 col-xs-12">
                    {{ field.errors }}
                    <span class="help-block">{{ field.help_text }}</span>
                </div>
            {% endif %}
        </div>
    {% endfor %}
    </div>
{% endblock %}

{% block footer_page_script %}
    <script>
        var skintypeEditPageVue = new CommonFormPageVue({
            data: {
                // API
                list_api_tag: 'api:skintype-list',
                detail_api_tag: 'api:skintype-detail',
                product_detail_api_tag: 'api:skintype-detail',
                delete_api_tag: 'api:skintype-delete',
                // page
                create_url_tag: 'analysis:skintype-add',
                list_url_tag: 'analysis:skintype-list',
                update_url_tag: 'analysis:skintype-update',
                detail_url_tag: 'analysis:skintype-detail',
                list_url: Urls['api:skintype-list']()
            }
        });
    </script>
{% endblock %}

apps/analysis/templates/analysis/skintype_list.html
{% extends "adminlte/common_list.html" %}
{% load static %}

{% block common_list_buttons %}
{% endblock %}

{% block item_buttons %}
    <td class="text-right hidden-sm hidden-xs">
        <template v-if="detail_url_tag">
            <a data-toggle="tooltip" data-placement="bottom" data-original-title="View"
               href="#[item.detail_url]" class="btn btn-info btn-sm detail-btn"
               data-pk="#[item.id]">
                <i class="fa fa-lg fa-bars fa-inverse"></i>
            </a>
        </template>

        <template v-if="update_url_tag">
            <a data-toggle="tooltip" data-placement="bottom" data-original-title="Edit"
               href="#[item.edit_url]?from_page={!! currentPage !!}&search={!! search_keyword !!}" class="btn btn-warning btn-sm edit-btn"
               data-pk="#[item.id]">
                <i class="fa fa-lg fa-pencil fa-inverse"></i>
            </a>
        </template>
    </td>
{% endblock %}

{% block common_list_footer_page_script %}
    <script type="text/javascript" src="{% static 'js/analysis/skintype_list.min.js' %}"></script>
{% endblock %}

apps/analysis/templates/analysis/word_form.html
{% extends "adminlte/common_form.html" %}
{% load static adminlte_tags %}

{% block form_content %}
    <div class="col-xs-12">
    {% for field in form %}
        <div class="form-group {% if field.errors %}error{% endif %} {% if field.is_hidden %}hide{% endif %}">
            <label for="id_{{ field.name }}" class="col-sm-2 col-xs-3 control-label">{{ field.label }}</label>
            <div class="col-sm-6 col-xs-9">
                {{ field }}
            </div>
            {% if field.errors %}
                <div class="col-sm-4 col-xs-12">
                    {{ field.errors }}
                    <span class="help-block">{{ field.help_text }}</span>
                </div>
            {% endif %}
        </div>
    {% endfor %}
    </div>
{% endblock %}

{% block footer_page_script %}
    <script>
        var wordEditPageVue = new CommonFormPageVue({
            data: {
                // API
                list_api_tag: 'api:word-list',
                detail_api_tag: 'api:word-detail',
                product_detail_api_tag: 'api:word-detail',
                delete_api_tag: 'api:word-delete',
                // page
                create_url_tag: 'analysis:word-add',
                list_url_tag: 'analysis:word-list',
                update_url_tag: 'analysis:word-update',
                detail_url_tag: 'analysis:word-detail',
                list_url: Urls['api:word-list']()
            }
        });
    </script>
{% endblock %}

apps/analysis/templates/analysis/word_list.html
{% extends "adminlte/common_list.html" %}
{% load static %}

{% block common_list_footer_page_script %}
    <script type="text/javascript" src="{% static 'js/analysis/word_list.min.js' %}"></script>
{% endblock %}