apps/weixin/urls.py
# coding=utf-8
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from rest_framework.routers import DefaultRouter
from core.api.routers import PostHackedRouter
from . import views


urlpatterns = []

# urls for page
urlpatterns += (
    url(r'^login/$', views.wx_login, name='login'),
    url(r'^auth/$', views.wx_auth, name='auth'),
    url(r'^index/$', views.wx_index, name='index'),
    url(r'^wxuser/list/$', views.WxUserListView.as_view(), name='wxuser-list'),
    url(r'^wxuser/(?P<pk>\d+)/$', views.WxUserDetailView.as_view(), name='wxuser-detail'),
    # url(r'^pay_notify', views.wx_pay_notify, name='pay_notify'),
)

config/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.views import serve

# from wagtail.wagtailadmin import urls as wagtailadmin_urls
# from wagtail.wagtailcore import urls as wagtail_urls
# from wagtail.wagtaildocs import urls as wagtaildocs_urls
# from wagtail.wagtailimages import urls as wagtailimages_urls
# from apps.wagtail.search.views import search as wagtail_search

from core.auth_user.views import ChangePasswordView
from core import auth_user
from core.auth_user.forms import CustomPasswordResetForm, CustomSetPasswordForm


def if_installed(appname, *args, **kwargs):
    ret = url(*args, **kwargs)
    if appname not in settings.INSTALLED_APPS:
        ret.resolve = lambda *args: None
    return ret


wagtail_urlpatterns = [
    # url(r'^admin/', include(wagtailadmin_urls)),
    # url(r'^documents/', include(wagtaildocs_urls)),
    # url(r'^images/', include(wagtailimages_urls)),
    # url(r'^search/$', wagtail_search, name='wagtail_search'),
    # url(r'^pages/', include(wagtail_urls)),
]

apps_urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('apps.dashboard.urls', namespace='dashboard')),
    url(r'^', include('core.auth_user.urls', namespace='users')),
    url(r'^brand/', include('apps.brand.urls', namespace='brand')),
    url(r'^product/', include('apps.product.urls', namespace='product')),
    url(r'^premium_product/', include('apps.premium_product.urls', namespace='premium_product')),
    url(r'^analysis/', include('apps.analysis.urls', namespace='analysis')),
    url(r'^survey/', include('apps.survey.urls', namespace='survey')),
    url(r'^report/', include('apps.report.urls', namespace='report')),
    url(r'^wx/', include('apps.weixin.urls', namespace='weixin')),
]

# REST API
api_urlpatterns = [
    url(r'^wx/', include('apps.weixin.api.urls')),
    url(r'^brand/', include('apps.brand.api.urls')),
    url(r'^product/', include('apps.product.api.urls')),
    url(r'^premium_product/', include('apps.premium_product.api.urls')),
    url(r'^analysis/', include('apps.analysis.api.urls')),
    url(r'^survey/', include('apps.survey.api.urls')),
    url(r'^report/', include('apps.report.api.urls')),
]

urlpatterns = wagtail_urlpatterns + apps_urlpatterns + [
    # REST API
    url(r'^api/', include(api_urlpatterns, namespace='api')),

    # auth
    url('^auth/change-password/$', ChangePasswordView.as_view(), name='change_password'),
    url('^auth/change-password-done/$', auth_user.views.ChangePasswordDoneView.as_view(), name='password_change_done'),

    # password reset
    url(r'^password/reset/$', auth_views.password_reset, {'template_name': 'adminlte/password_reset_form.html',
                                                          'email_template_name': 'adminlte/password_reset_email.html',
                                                          'password_reset_form': CustomPasswordResetForm},
        name='password_reset'),
    url(r'^password/reset/done/$', auth_views.password_reset_done,
        {'template_name': 'adminlte/password_reset_done.html'},
        name='password_reset_done'),
    url(r'^password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', auth_views.password_reset_confirm,
        {'template_name': 'adminlte/password_reset_confirm.html',
         'set_password_form': CustomSetPasswordForm},
        name='password_reset_confirm'),
    url(r'^password/reset/complete/$', auth_views.password_reset_complete,
        {'template_name': 'adminlte/password_reset_complete.html'},
        name='password_reset_complete'),

    # dbsettings
    # url(r'^djadmin/settings/', include('dbsettings.urls')),

    # django-tinymce
    # url(r'^tinymce/', include('tinymce.urls')),

    url(r'^MP_verify_aVcytWJVmPok60D5\.txt$', serve, kwargs={'path': 'MP_verify_aVcytWJVmPok60D5.txt'}),

    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:
    # url(r'^home/', include(wagtail_urls)),
]

if settings.DEBUG:
    from rest_framework_swagger.views import get_swagger_view
    from django.conf.urls.static import static

    urlpatterns += [
        url(r'^api/docs/$', get_swagger_view(title='OZSales API'))
    ]

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/adminlte/templates/adminlte/base.html
{% load static %}
{% get_static_prefix as STATIC_PREFIX %}
<!DOCTYPE html>
<html lang="en-us">
<head>
    <meta charset="UTF-8">
    <title>
        {% block base_head_title %}{{ page_title }}{% endblock %} |
        {% block base_head_title_system_name %}{{ page_system_name }}{% endblock %}
    </title>

    {% block blockrobots %}
        <link rel="shortcut icon" href="{{ STATIC_PREFIX }}images/favicon.ico">
        <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    {% endblock %}

    {% block header_base_style %}
        {% include "adminlte/includes/style.html" %}
        {% include "adminlte/includes/header_script.html" %}
        <!--[if lt IE 9]>
            <script src="http://cdn.bootcss.com/html5shiv/r29/html5.min.js"></script>
            <script src="http://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
    {% endblock %}
    {% block header_base_script %}{{ form.media }}{% endblock %}
    {% block header_page_script %}{% endblock %}
</head>

{% block base_body %}
    <body class="{% block base_body_class %}skin-blue sidebar-mini{% endblock %}">
    <input type="hidden" name="adminlte_page_app_name" id="adminlte_page_app_name" value="{{ page_app_name }}"/>
    <input type="hidden" name="adminlte_page_model_name" id="adminlte_page_model_name" value="{{ page_model_name }}"/>
    <input type="hidden" name="adminlte_page_user_name" id="adminlte_page_user_name"
           value="{{ request.user.username }}"/>

    {% block base_body_inner %}
        <div class="wrapper">

            {% block header %}
                {% include "adminlte/includes/header.html" %}
            {% endblock %}

            {% block menu %}
                {% include "adminlte/includes/menu.html" %}
            {% endblock %}

            <div class="content-wrapper">
                {% block base_content_wrapper_inner %}
                    <section class="content-header">
                        {% block base_content_header %}
                            <h1 class="hidden-sm hidden-xs">
                                {% block content_title %}
                                    {{ default_dashboard_title }}
                                {% endblock %}
                                <small>
                                    {% block base_content_header_small_title %}
                                    {% endblock %}
                                </small>
                            </h1>

                            {% block breadcrumb %}
                                <ol class="breadcrumb">
                                    <li>
                                        <a href="/dashboard">
                                            <i class="fa fa-dashboard"></i> {{ default_dashboard_title }}
                                        </a>
                                    </li>
                                    {% if page_title != default_dashboard_title %}
                                        <li class="active">
                                            {% if page_app_name and page_model_name %}
                                                {% with page_app_name|add:":"|add:page_model_name|add:"-list" as list_url %}
                                                    <a href="{% url list_url %}">
                                                        {{ page_model_verbose_name }}
                                                    </a>
                                                {% endwith %}
                                            {% else %}
                                                {{ page_title }}
                                            {% endif %}
                                        </li>
                                    {% endif %}
                                    {% if object != None %}
                                        <li class="active">{{ page_title }}详情</li>
                                    {% endif %}
                                </ol>
                            {% endblock %}
                        {% endblock %}
                    </section>
                    <section class="content">
                        {% block content %}
                            {{ content }}
                        {% endblock %}
                    </section>
                {% endblock %}
            </div>
            {% include "adminlte/includes/footer.html" %}
            {% if user.is_superuser %}
                {% include "adminlte/includes/control_sidebar.html" %}
            {% endif %}
        </div>
    {% endblock %}

    {% include "adminlte/includes/footer_script.html" %}
    {% block footer_base_script %}{% endblock %}
    {% block footer_page_script %}{% endblock %}
    </body>
{% endblock %}
</html>

core/adminlte/templates/adminlte/change-password-done.html
{% extends "adminlte/base.html" %}

{% block content_title %}
    修改密码
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <p>密码修改操作成功! 请您牢记新密码，
                <a href="/">点这里回到首页</a></p>
        </div>
    </div>
{% endblock %}

core/adminlte/templates/adminlte/change-password.html
{% extends "adminlte/base.html" %}

{% block content_title %}
    修改密码
{% endblock %}

{% block base_head_style %}
    <style type="text/css">
        .errorlist {
            list-style: none;
            padding: 0;
            color: red;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="box box-primary">
                <div class="box-body">
                    <div class="row">
                        <div class="col-md-5 col-sm-12">
                            {% if 'success' in form %}
                                {{ form.success }}
                            {% endif %}
                            <form method="post" action="" role="form"
                                  id="changePasswordForm">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="id_old_password">旧密码:</label>
                                    <input id="id_old_password" maxlength="20"
                                           name="old_password" type="password"
                                           class="form-control"
                                           placeholder="请输入当前密码"/>
                                    {{ form.old_password.errors }}
                                </div>
                                <div class="form-group">
                                    <label for="id_new_password1">新密码:</label>
                                    <input id="new_password1" maxlength="20"
                                           name="new_password1" type="password"
                                           class="form-control"
                                           placeholder="请输入新密码"/>
                                    {{ form.new_password1.errors }}
                                </div>
                                <div class="form-group">
                                    <label for="id_new_password2">确认新密码:</label>
                                    <input id="new_password2" maxlength="20"
                                           name="new_password2" type="password"
                                           class="form-control"
                                           placeholder="请再次输入新密码"/>
                                    {{ form.new_password2.errors }}
                                </div>
                                <div class="clearfix"></div>
                                <button type="submit" class="btn btn-primary">
                                    保 存
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

core/adminlte/templates/adminlte/common_detail.html
{% extends "adminlte/base.html" %}
{% load adminlte_tags %}

{% block content_title %}
    <b>{{ object }} 详情</b>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-12 full-width">
            <div class="box box-info">
                <div class="box-header with-border">
                    {% block form_title %}
                        <h3 class="box-title">{{ object }}</h3>
                    {% endblock %}
                </div>

                {% block form_table %}
                    <div class="box-body table-responsive">
                        <table class="table">
                            {% block table_content %}
                                {% for field in form.fields %}
                                    {% ifnotequal field 'id' %}
                                        <tr>
                                            <th>{{ object|render_field_label:field }}</th>
                                            <td>{{ object|render_field_value:field|safe }}</td>
                                        </tr>
                                    {% endifnotequal %}
                                {% endfor %}
                            {% endblock %}
                        </table>
                    </div>
                {% endblock %}

                <div class="box-footer">
                </div>
            </div>
        </div>
    </div>
{% endblock %}

core/adminlte/templates/adminlte/common_list.html
{% extends "adminlte/base.html" %}
{% load static adminlte_tags %}
{% block content_title %}
  {{ page_title }}
{% endblock %}

{% block content %}
  <div class="row {{ page_model_name }}_list_content" id="commonDataTableRow">
    <div class="col-xs-12 full-width">
      <div class="box box-info">

        {% block content_header %}
        <div class="box-header with-border">
          {% block common_list_buttons %}
            <div class="col-xs-5 col-sm-6">
                {% if page_model_perms.add %}
                  <a class="btn btn-primary" id="create">
                    <i class="fa fa-plus"></i>新增
                  </a>
                {% endif %}
                {% if page_model_perms.delete %}
                  <a class="btn btn-danger hidden-sm hidden-xs" v-on:click="removeSelected">
                    <i class="fa fa-trash-o"></i>
                    删除
                  </a>
                {% endif %}
            </div>
            {% endblock %}

            {% block search_box %}
            <div class="col-xs-7 col-sm-6 pull-right">
              <div class="input-group">
                <input type="text" name="search" id="tableSearch" placeholder="关键字" v-on:keypress.13="search"
                       class="form-control input-sm pull-right">

                <div class="input-group-btn">
                  <button class="btn btn-sm btn-default" v-on:click="resetSearch">
                    <i class="fa fa-times-circle"></i>
                  </button>
                  <button class="btn btn-sm btn-default" v-on:click="search">
                    <i class="fa fa-search"></i>
                  </button>
                </div>
              </div>
            </div>
            {% endblock %}
        </div>

        {% include "adminlte/includes/messages.html" %}

        <!-- /.box-header -->
        {% endblock %}

        {% block tab_content %}
          <div class="box-body table-responsive no-padding">
            <table class="table table-hover" id="commonTable">
              <thead>
              <tr>
                {% block table_head %}
                  <th class="text-center" style="width:65px;">
                    <input type="checkbox" name="checkboxAllRow" class="checkboxAllRow" v-on:click="toggleAllBox"/>
                  </th>
                  {% for title in table_titles %}
                    {% with 'ID,id,'|split:',' as tlist %}
                      {% if title in tlist %}
                        <th class="hidden-sm hidden-xs">{{ title }}</th>
                      {% else %}
                        <th>{{ title }}</th>
                      {% endif %}
                    {% endwith %}
                  {% endfor %}
                {% endblock %}
              </tr>
              </thead>
              {% block table_row %}
                <tbody v-for="item in items">
                <tr>
                  <td class="text-center hidden-sm hidden-x">
                    ##[$index+1]
                    <input type="checkbox" class="minimal" name="checkboxRow" value="#[item.id]"/>
                  </td>
                  {% for field in table_fields %}
                    {% if field == 'id' %}
                      {% block item_buttons %}
                        <td class="text-right hidden-sm hidden-xs">
                          <template v-if="detail_url_tag">
                          {% if page_model_perms.view %}
                            <a data-toggle="tooltip" data-placement="bottom" data-original-title="View"
                               href="#[item.detail_url]" class="btn btn-info btn-sm detail-btn" data-pk="#[item.id]">
                              <i class="fa fa-lg fa-bars fa-inverse"></i>
                            </a>
                          {% endif %}
                          </template>

                          <template v-if="update_url_tag">
                          {% if page_model_perms.change %}
                            <a data-toggle="tooltip" data-placement="bottom" data-original-title="Edit"
                               href="#[item.edit_url]?from_page={!! currentPage !!}&search={!! search_keyword !!}" class="btn btn-warning btn-sm edit-btn" data-pk="#[item.id]">
                              <i class="fa fa-lg fa-pencil fa-inverse"></i>
                            </a>
                          {% endif %}
                          </template>

                          <template v-if="delete_api_tag">
                          {% if page_model_perms.delete %}
                            <a data-toggle="tooltip" data-placement="bottom" data-original-title="Delete"
                               data-pk="#[item.id]" v-on:click="removeOne" href="javascript:void(0);"
                               class="btn btn-danger btn-sm delete-btn">
                              <i class="fa fa-lg fa-trash-o fa-inverse"></i>
                            </a>
                          {% endif %}
                          </template>
                        </td>
                      {% endblock %}
                    {% else %}
                      <td>
                        {!! item.{{ field }} !!}
                      </td>
                    {% endif %}
                  {% endfor %}
                </tr>
                </tbody>
              {% endblock %}
            </table>
          </div>
        {% endblock %}

        {% block common_list_pagination %}
          <div class="box-footer clearfix">
            {% include 'adminlte/common_list_pagination.html' %}
          </div>
        {% endblock %}
      </div>
    </div>
  </div>
{% endblock %}

{% block footer_page_script %}
  <script type="text/javascript" src="{% static 'adminlte/js/common-list-page-base.js' %}"></script>
  {% block common_list_footer_page_script %}
    <script type="text/javascript" src="{% static 'adminlte/js/common-list-page.js' %}"></script>
  {% endblock %}
{% endblock %}

core/adminlte/templates/adminlte/common_list_pagination.html
<div class="form-inline" align="center">
<ul class="pagination pagination-sm no-margin form-group">
    <li v-if="currentPage > 1">
        <a href="javascript:void(0);" page="1" v-on:click="page" class="text-bold">首页</a>
    </li>
    <li v-if="currentPage == 1" class="disabled">
        <a href="javascript:void(0);">首页</a>
    </li>
    <li v-if="currentPage > 1">
        <a href="javascript:void(0);" page="#[currentPage-1]" v-on:click="page" class="text-bold">上页</a>
    </li>
    <li v-if="currentPage == 1" class="disabled">
        <a href="javascript:void(0);">上页</a>
    </li>
    <li v-if="currentPage < totalPage">
        <a href="javascript:void(0);" page="#[currentPage+1]" v-on:click="page" class="text-bold">下页</a>
    </li>
    <li v-if="currentPage == totalPage" class="disabled">
        <a href="javascript:void(0);">下页</a>
    </li>
    <li v-if="currentPage < totalPage">
        <a href="javascript:void(0);" page="#[totalPage]" v-on:click="page" class="text-bold">末页</a>
    </li>
    <li v-if="currentPage == totalPage" class="disabled">
        <a href="javascript:void(0);">末页</a>
    </li>
    <li v-on:click="reload" class="text-bold" id="current_page">
        <a href="javascript:void(0);">刷新</a>
    </li>
</ul>
<div class="form-group">
    &nbsp;&nbsp;&nbsp;共 #[count] 条数据, 每页 #[perPage] 条, 第 #[currentPage]/#[totalPage] 页
</div>
</div>

core/adminlte/templates/adminlte/index.html
{% extends "adminlte/base.html" %}

{% block content %}
    <div class="row">
        待完善
        {% comment %}<div class="col-lg-3 col-xs-6">
            <!-- small box -->
            <div class="small-box bg-yellow">
                <div class="inner">
                    <h3>{{ staff_count }}</h3>

                    <p><strong>员工总数</strong></p>
                </div>
                <div class="icon">
                    <i class="ion ion-person-add"></i>
                </div>
                <a href="{% url 'common:common_list_page' 'organization' 'staff' %}" class="small-box-footer">查看更多 <i
                        class="fa fa-arrow-circle-right"></i></a>
            </div>
        </div>
        <div class="col-lg-3 col-xs-6">
            <div class="small-box bg-aqua">
                <div class="inner">
                    <h3>150</h3>

                    <p><strong>订单数量</strong></p>
                </div>
                <div class="icon">
                    <i class="ion ion-bag"></i>
                </div>
                <a href="#" class="small-box-footer">查看更多 <i
                        class="fa fa-arrow-circle-right"></i></a>
            </div>
        </div>
        <div class="col-lg-3 col-xs-6">
            <div class="small-box bg-green">
                <div class="inner">
                    <h3>53<sup style="font-size: 20px">%</sup></h3>

                    <p>Bounce Rate</p>
                </div>
                <div class="icon">
                    <i class="ion ion-stats-bars"></i>
                </div>
                <a href="#" class="small-box-footer">More info <i
                        class="fa fa-arrow-circle-right"></i></a>
            </div>
        </div>

        <div class="col-lg-3 col-xs-6">
            <div class="small-box bg-red">
                <div class="inner">
                    <h3>65</h3>
                    <p>Unique Visitors</p>
                </div>
                <div class="icon">
                    <i class="ion ion-pie-graph"></i>
                </div>
                <a href="#" class="small-box-footer">More info <i
                        class="fa fa-arrow-circle-right"></i></a>
            </div>
        </div>{% endcomment %}
    </div>
{% endblock %}

core/adminlte/templates/adminlte/login.html
{% extends "adminlte/base.html" %}
{% load static %}

{% block base_head_title %}Login{% endblock %}

{% block base_body %}
<body class="hold-transition login-page">
  <div class="login-box">
  <div class="login-logo">
      <a href="#"><b>Aimeipin</b> Skin</a>
  </div>
  <!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg">登陆系统</p>

    {% if messages %}
      <div class="row">
          <div class="col-xs-12">
            {% for message in messages %}`
              <span class="alert-{{ message.tags }}">{{ message }}</span>
              <br/><br/>
            {% endfor %}
          </div>
      </div>
    {% endif %}

    <form action="{% url "users:login" %}" method="post">
      <div class="form-group has-feedback{% if form.mobile.errors %} has-error{% endif %}">
        <input id="id_mobile" type="text" name="mobile" class="form-control" placeholder="{{ form.mobile.errors.as_text|default:"手机号码或电子邮件" }}"{% if form.mobile.value and not form.mobile.errors%} value="{{ form.mobile.value }}"{% endif %}
        {% if not form.mobile.value %} autofocus{% endif %}>
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
      </div>
      <div class="form-group has-feedback{% if form.password.errors or form.non_field_errors %} has-error{% endif %}">
        <input name="password" id="id_password" type="password" class="form-control" placeholder="{{ form.password.errors.as_text|default:"密 码" }}"
        {% if form.mobile.value %} autofocus{% endif %}>
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
      </div>

    {% if form.non_field_errors %}
        <div class="row">
            <div class="col-xs-12 text-center">
                <span class="alert-error">{{ form.non_field_errors.as_text }}</span>
            </div>
        </div>
    {% endif %}

      <div class="row">
        <div class="col-xs-8">
          <div class="checkbox icheck">
            <label>
              <input name="remember_me" type="checkbox" checked> 记住我
            </label>
          </div>
        </div>
        <!-- /.col -->
        <div class="col-xs-4">
          <input type="hidden" name="next" value="{{ next }}" />
          <button type="submit" class="btn btn-primary btn-block btn-flat">登 陆</button>
        </div>
        <!-- /.col -->
      </div>
    </form>

    <div class="social-auth-links">
        <p class="text-center">- OR -</p>
        <a class="btn-block" href="{% url 'password_reset' %}">忘记密码?</a>
    </div>

  </div>
  <!-- /.login-box-body -->
  </div>
  <!-- /.login-box -->

  <!-- iCheck -->
  <script>
    $(function () {
      $('input').iCheck({
        checkboxClass: 'icheckbox_square-blue',
        radioClass: 'iradio_square-blue',
        increaseArea: '20%' // optional
      });
    });
  </script>
</body>
{% endblock %}

core/adminlte/templates/adminlte/password_reset_complete.html
{% extends "adminlte/base.html" %}
{% load static %}

{% block base_head_title %}重设密码{% endblock %}

{% block base_body %}
<body class="hold-transition login-page">
  <div class="login-box">
  <div class="login-logo">
    <a href="#"><b>Aimeipin</b> Skin</a>
  </div>
  <!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg">重设密码</p>

    {% if messages %}
      <div class="row">
          <div class="col-xs-12">
            {% for message in messages %}
              <span class="alert-{{ message.tags }}">{{ message }}</span>
              <br/><br/>
            {% endfor %}
          </div>
      </div>
    {% endif %}

    <div class="widget-body">
        <p>重设密码完成.</p>
        <p>请<a href="{% url 'member:member-login' %}">点击登陆</a>.</p>
    </div>
  </div>
  <!-- /.login-box-body -->
  </div>
  <!-- /.login-box -->

</body>
{% endblock %}

core/adminlte/templates/adminlte/password_reset_confirm.html
{% extends "adminlte/base.html" %}
{% load static %}

{% block base_head_title %}重设密码{% endblock %}

{% block header_base_style %}{% endblock %}


{% block base_body %}
    <body class="hold-transition register-page">
    <div class="register-box">
        <div class="register-logo">
            <a href="#"><b>Aimeipin</b> Skin</a>
        </div>

        <div class="register-box-body">
            <p class="login-box-msg">重设密码</p>
            <form action="" method="post">
                {% if validlink %}
                {% csrf_token %}
                <div class="form-group has-feedback{% if form.new_password1.errors %} has-error{% endif %}">
                    <input id="id_new_password1" name="new_password1" type="password" class="form-control"
                    placeholder="{{ form.new_password1.errors.as_text|default:"密 码" }}">
                    <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                </div>
                <div class="form-group has-feedback{% if form.new_password2.errors %} has-error{% endif %}">
                    <input  id="id_new_password2" name="new_password2" type="password" class="form-control"
                            placeholder="{{ form.new_password2.errors.as_text|default:"重复密码" }}">
                    <span class="glyphicon glyphicon-log-in form-control-feedback"></span>
                </div>

                <div class="row">
                    <!-- /.col -->
                    <div class="col-xs-4 col-xs-offset-4">
                        <button type="submit" class="btn btn-primary btn-block btn-flat">提 交</button>
                    </div>
                    <!-- /.col -->
                </div>
                {% else %}
                    <p>本链接已失效，请<a href="{% url 'member:member-login' %}">重新登陆</a>.</p>
                {% endif %}
            </form>
        </div>
        <!-- /.form-box -->
    </div>
    <!-- /.register-box -->
    </body>
{% endblock %}

{% block footer_page_script %}{% endblock %}

core/adminlte/templates/adminlte/password_reset_done.html
{% extends "adminlte/base.html" %}
{% load static %}

{% block base_head_title %}重设密码{% endblock %}

{% block base_body %}
<body class="hold-transition login-page">
  <div class="login-box">
  <div class="login-logo">
    <a href="#"><b>Aimeipin</b> Skin</a>
  </div>
  <!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg">重设密码</p>

    {% if messages %}
      <div class="row">
          <div class="col-xs-12">
            {% for message in messages %}
              <span class="alert-{{ message.tags }}">{{ message }}</span>
              <br/><br/>
            {% endfor %}
          </div>
      </div>
    {% endif %}

    <div class="widget-body">
        <p>验证邮件已发送，请登陆电子邮箱查看.</p>
        <p>重设密码后，请<a href="{% url 'member:member-login' %}">继续登陆</a>.</p>
    </div>
  </div>
  <!-- /.login-box-body -->
  </div>
  <!-- /.login-box -->

</body>
{% endblock %}