apps/product/api/urls.py
from django.conf.urls import url
from core.api.routers import PostHackedRouter
from . import views

router = PostHackedRouter()
router.include_root_view = False

# reverse('api:brand-list'), reverse('api:brand-detail', kwargs={'pk': 1})
router.register(r'product', views.ProductViewSet, base_name='product')

urlpatterns = [
    url(r'^product/autocomplete/$', views.ProductAutocompleteAPIView.as_view(), name='product-autocomplete'),
    url(r'^product/search/$', views.ProductSearchAPIView.as_view(), name='product-search'),
]

urlpatterns += router.urls

apps/product/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^product/add/$', views.ProductAddView.as_view(), name="product-add"),
    url(r'^product/$', views.ProductListView.as_view(), name="product-list"),
    url(r'^product/(?P<pk>\d+)/$', views.ProductDetailView.as_view(), name="product-detail"),
    url(r'^product/(?P<pk>\d+)/edit/$', views.ProductUpdateView.as_view(), name="product-update"),
    url(r'^product/import/$', views.ProductImportView.as_view(), name="product-import"),
]

config/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.views import serve

# from wagtail.wagtailadmin import urls as wagtailadmin_urls
# from wagtail.wagtailcore import urls as wagtail_urls
# from wagtail.wagtaildocs import urls as wagtaildocs_urls
# from wagtail.wagtailimages import urls as wagtailimages_urls
# from apps.wagtail.search.views import search as wagtail_search

from core.auth_user.views import ChangePasswordView
from core import auth_user
from core.auth_user.forms import CustomPasswordResetForm, CustomSetPasswordForm


def if_installed(appname, *args, **kwargs):
    ret = url(*args, **kwargs)
    if appname not in settings.INSTALLED_APPS:
        ret.resolve = lambda *args: None
    return ret


wagtail_urlpatterns = [
    # url(r'^admin/', include(wagtailadmin_urls)),
    # url(r'^documents/', include(wagtaildocs_urls)),
    # url(r'^images/', include(wagtailimages_urls)),
    # url(r'^search/$', wagtail_search, name='wagtail_search'),
    # url(r'^pages/', include(wagtail_urls)),
]

apps_urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('apps.dashboard.urls', namespace='dashboard')),
    url(r'^', include('core.auth_user.urls', namespace='users')),
    url(r'^brand/', include('apps.brand.urls', namespace='brand')),
    url(r'^product/', include('apps.product.urls', namespace='product')),
    url(r'^premium_product/', include('apps.premium_product.urls', namespace='premium_product')),
    url(r'^analysis/', include('apps.analysis.urls', namespace='analysis')),
    url(r'^survey/', include('apps.survey.urls', namespace='survey')),
    url(r'^report/', include('apps.report.urls', namespace='report')),
    url(r'^wx/', include('apps.weixin.urls', namespace='weixin')),
]

# REST API
api_urlpatterns = [
    url(r'^wx/', include('apps.weixin.api.urls')),
    url(r'^brand/', include('apps.brand.api.urls')),
    url(r'^product/', include('apps.product.api.urls')),
    url(r'^premium_product/', include('apps.premium_product.api.urls')),
    url(r'^analysis/', include('apps.analysis.api.urls')),
    url(r'^survey/', include('apps.survey.api.urls')),
    url(r'^report/', include('apps.report.api.urls')),
]

urlpatterns = wagtail_urlpatterns + apps_urlpatterns + [
    # REST API
    url(r'^api/', include(api_urlpatterns, namespace='api')),

    # auth
    url('^auth/change-password/$', ChangePasswordView.as_view(), name='change_password'),
    url('^auth/change-password-done/$', auth_user.views.ChangePasswordDoneView.as_view(), name='password_change_done'),

    # password reset
    url(r'^password/reset/$', auth_views.password_reset, {'template_name': 'adminlte/password_reset_form.html',
                                                          'email_template_name': 'adminlte/password_reset_email.html',
                                                          'password_reset_form': CustomPasswordResetForm},
        name='password_reset'),
    url(r'^password/reset/done/$', auth_views.password_reset_done,
        {'template_name': 'adminlte/password_reset_done.html'},
        name='password_reset_done'),
    url(r'^password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', auth_views.password_reset_confirm,
        {'template_name': 'adminlte/password_reset_confirm.html',
         'set_password_form': CustomSetPasswordForm},
        name='password_reset_confirm'),
    url(r'^password/reset/complete/$', auth_views.password_reset_complete,
        {'template_name': 'adminlte/password_reset_complete.html'},
        name='password_reset_complete'),

    # dbsettings
    # url(r'^djadmin/settings/', include('dbsettings.urls')),

    # django-tinymce
    # url(r'^tinymce/', include('tinymce.urls')),

    url(r'^MP_verify_aVcytWJVmPok60D5\.txt$', serve, kwargs={'path': 'MP_verify_aVcytWJVmPok60D5.txt'}),

    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:
    # url(r'^home/', include(wagtail_urls)),
]

if settings.DEBUG:
    from rest_framework_swagger.views import get_swagger_view
    from django.conf.urls.static import static

    urlpatterns += [
        url(r'^api/docs/$', get_swagger_view(title='OZSales API'))
    ]

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/product/api/views.py
import logging

import sys
from django.db.models import Q
from dal import autocomplete
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework import permissions, filters

from core.api.filters import PinyinSearchFilter
from core.utils.string import include_non_asc
from core.django.autocomplete import HansSelect2ViewMixin
from core.api.views import CommonViewSet
from ..models import Product
from . import serializers

log = logging.getLogger(__name__)


class ProductViewSet(CommonViewSet):
    """ API views for Product """
    queryset = Product.objects.all()
    serializer_class = serializers.ProductSerializer
    permission_classes = [permissions.AllowAny]
    filter_fields = ['name_en', 'name_cn', 'brand__id', 'brand__name_cn', 'brand__name_en']
    search_fields = ['name_cn', 'brand__name_cn', 'alias']
    pinyin_search_fields = ['name_cn', 'name_en', 'pinyin', 'brand__name_en']  # search only input are all ascii chars
    filter_backends = (DjangoFilterBackend,
                       PinyinSearchFilter,
                       filters.OrderingFilter)


class ProductAutocompleteAPIView(HansSelect2ViewMixin, autocomplete.Select2QuerySetView):
    model = Product
    paginate_by = 20

    # create_field = 'name_cn'
    #
    # def create_object(self, text):
    #     return self.get_queryset().create(**{self.create_field: text, 'seller': self.request.profile})

    def get_queryset(self):
        qs = Product.objects.all()
        brand_id = self.request.GET.get('brand_id', '')
        category = self.forwarded.get('category') or self.request.GET.get('category', '')
        if brand_id:
            qs = qs.filter(brand__id=brand_id)
        if category:
            qs = qs.filter(category=category)

        if include_non_asc(self.q):
            qs = qs.filter(
                Q(name_cn__icontains=self.q) | Q(brand__name_cn__icontains=self.q) | Q(alias__icontains=self.q))
        else:
            # all ascii, number and letter
            key = self.q.lower()
            if key:
                qs = qs.filter(
                    Q(pinyin__icontains=key) | Q(name_en__icontains=key) | Q(name_cn__icontains=key))
        return qs

    def get_results(self, context):
        return [
            {
                'id': self.get_result_value(result),
                'text': self.get_result_label(result),
                'image': result.pic.thumbnail.url if result.pic else None,
            } for result in context['object_list']
        ]


class ProductSearchAPIView(ProductAutocompleteAPIView):
    paginate_by = sys.maxsize

    # def get_queryset(self):
    #     brand_id = self.request.GET.get('brand_id', '')
    #     if not self.q and not brand_id:
    #         return Product.objects.none()
    #     return super(ProductSearchAPIView, self).get_queryset()

apps/product/views.py
from django.contrib import messages
from django.db.models import Q
from django.core.exceptions import ValidationError
from django.http import HttpResponseRedirect
from django.views.generic import ListView, CreateView, UpdateView
from braces.views import SuperuserRequiredMixin
from django.views.generic.edit import ProcessFormView, FormView
from pyexcel_xls import get_data

from apps.product.forms import ProductAnalysisFormSet, ProductImportForm  # ,ProductIngredientFormSet
from core.django.views import CommonContextMixin
from .models import Product, Brand, ProductIngredient
from . import forms


class ProductListView(SuperuserRequiredMixin, CommonContextMixin, ListView):
    model = Product
    template_name_suffix = '_list'

    def get_context_data(self, **kwargs):
        context = super(ProductListView, self).get_context_data(**kwargs)
        context['table_titles'] = ['Pic', 'Name', 'Brand']
        context['table_fields'] = ['pic', 'link', 'brand']
        context['brands'] = Brand.objects.all()
        return context


class ProductAddView(SuperuserRequiredMixin, CommonContextMixin, CreateView):
    model = Product
    form_class = forms.ProductAddForm
    template_name = 'product/product_form.html'

    def get_context_data(self, **kwargs):
        context = super(ProductAddView, self).get_context_data(**kwargs)
        context['table_titles'] = ['Pic', 'Name', 'Brand', '']
        context['table_fields'] = ['pic', 'link', 'brand', 'id']

        if self.request.POST:
            if self.object:
                context['productanalysis_formset'] = ProductAnalysisFormSet(
                    self.request.POST, self.request.FILES,
                    prefix='productanalysis_formset', instance=self.object,
                    queryset=self.object.productanalysis_set.order_by('oily_type', 'sensitive_type', 'pigment_type',
                                                                      'loose_type'))
            else:
                context['productanalysis_formset'] = ProductAnalysisFormSet(
                    self.request.POST, self.request.FILES,
                    prefix='productanalysis_formset', instance=self.object)
        else:
            if self.object:
                context['productanalysis_formset'] = ProductAnalysisFormSet(
                    prefix='productanalysis_formset', instance=self.object,
                    queryset=self.object.productanalysis_set.order_by('oily_type', 'sensitive_type', 'pigment_type',
                                                                      'loose_type'))
            else:
                context['productanalysis_formset'] = ProductAnalysisFormSet(
                    prefix='productanalysis_formset', instance=self.object)

        return context

    def form_valid(self, form):
        self.object = form.save()

        productanalysis_formset = ProductAnalysisFormSet(self.request.POST, self.request.FILES,
                                                         prefix='productanalysis_formset', instance=self.object)
        productanalysis_formset.instance = self.object

        if productanalysis_formset.is_valid():
            productanalysis_formset.save()
        else:
            messages.error(self.request, str(productanalysis_formset.errors))

        return HttpResponseRedirect(self.get_success_url())


class ProductUpdateView(ProductAddView):
    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        return ProcessFormView.get(self, request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return ProcessFormView.post(self, request, *args, **kwargs)


class ProductDetailView(CommonContextMixin, UpdateView):
    model = Product
    # template_name_suffix = '_form'
    fields = ['name_en', 'name_cn', 'pic', 'brand', 'avg_sell_price']


class ProductImportView(FormView):
    form_class = ProductImportForm
    template_name = 'product/product_import.html'

    def get_success_url(self):
        from django.urls import reverse
        return reverse('product:product-list')

    def form_valid(self, form):
        product_file = form.cleaned_data.get('product_file')
        current_row = None
        if product_file:
            file_ext = product_file.name.split('.')[-1]
            product_data = get_data(product_file, file_ext.lower())

            try:
                for table_name, table in product_data.items():
                    current_row = None
                    if len(table[0]) != 7 or table[0][0] != '产品拼音首字母':
                        raise ValidationError('Excel文件格式不正确，需包含"产品拼音首字母, 产品名称, 品牌, 英文名, 图片, 别名, 所属分类" 7列.')
                    for row in table[1:]:
                        current_row = row
                        self.process_product(row)
            except Exception as e:
                messages.error(self.request, '导入失败: %s, %s' % (current_row or '', e))
                return super(ProductImportView, self).form_invalid(form)

        component_file = form.cleaned_data.get('component_file')
        if component_file:
            file_ext = component_file.name.split('.')[-1]
            component_data = get_data(component_file, file_ext.lower())
            try:
                for table_name, table in component_data.items():
                    current_row = None
                    if len(table[0]) != 7 or table[0][0] != '产品':
                        raise ValidationError(
                            'Excel文件格式不正确，需包含"产品, 产品成分, 成分是否安全,（1安全、2不安全）, 活性因子（1是、2不是）, 是否导致起痘（1会、2不会）, 成分简介, 成分在产品中的作用" 7列.')
                    for row in table[1:]:
                        current_row = row
                        self.process_component(row)
            except Exception as e:
                messages.error(self.request, '导入失败: %s, %s' % (current_row or '', e))
                return super(ProductImportView, self).form_invalid(form)

        messages.success(self.request, '导入成功.')
        return super(ProductImportView, self).form_valid(form)

    def process_component(self, row):
        # 产品, 产品成分, 成分是否安全,（1安全、2不安全）, 活性因子（1是、2不是）, 是否导致起痘（1会、2不会）, 成分简介, 成分在产品中的作用
        if not row or len(row) < 2 or (not row[0] and not row[1]):
            return

        name_cn = row[0]
        component_name = row[1]
        safe = row[2] or '' if len(row) > 2 else ''
        is_live = row[3] or '' if len(row) > 3 else ''
        is_pox = row[4] or '' if len(row) > 4 else ''
        description = row[5] or '' if len(row) > 5 else ''
        effect = row[6] or '' if len(row) > 6 else ''
        is_live = True if is_live == '1' else False
        is_pox = True if is_pox == '1' else False

        component = ProductIngredient.objects.filter(name=component_name).first()
        if not component:
            component = ProductIngredient(name=component_name)
        component.safe = safe
        component.is_live = is_live
        component.is_pox = is_pox
        component.description = description
        component.effect = effect
        component.save()

        product = Product.objects.filter(name_cn=name_cn).first()
        if product:
            if not product.ingredients.filter(name=component_name).count():
                product.ingredients.add(component)

    def process_product(self, row):
        # 产品拼音首字母, 产品名称, 品牌, 英文名, 图片, 别名, 所属分类
        if not row or len(row) < 2 or not row[1]:
            return

        name_cn = row[1]
        brand_name = row[2] or '' if len(row) > 2 else ''
        name_en = row[3] or '' if len(row) > 3 else ''
        alias = row[5] or '' if len(row) > 5 else ''
        category = row[6] or '' if len(row) > 6 else ''
        if len(row) > 4 and row[4]:
            pic = 'product/%s.jpg' % row[4] if '.' not in row[4] else 'product/%s' % row[4]
        else:
            pic = None

        brand = Brand.objects.filter(Q(name_cn=brand_name) | Q(name_en=brand_name)).first() if brand_name else None
        product, created = Product.objects.get_or_create(name_cn=name_cn)
        product.brand = brand
        product.alias = alias
        product.name_en = name_en
        product.category = category
        product.pic = pic
        product.save()

apps/product/templates/product/_menu.html
{% load product_tags %}

<li class="treeview active">
    <a href="javascript:void(0)">
        <i class='fa fa-shopping-bag'></i>
        <b>产品库</b>

        <span class="pull-right-container">
            <small class="label pull-right bg-blue">{% product_counter %}</small>
        </span>
    </a>

    <ul class="treeview-menu menu-open" style="display: block;">
        <li>
            <a href="{% url 'product:product-add' %}" class="pull-right"><i class="fa fa-plus" aria-hidden="true"></i></a>
            <a href="{% url 'product:product-list' %}" class="main">
                <i class="fa fa-circle-o"></i>
                产品
            </a>
        </li>
        <li>
            <a href="{% url 'product:product-import' %}" class="main">
                <i class="fa fa-circle-o"></i>
                批量导入
            </a>
        </li>
    </ul>
</li>

apps/product/templates/product/product_form.html
{% extends "adminlte/common_form.html" %}
{% load static adminlte_tags %}

{% block form_content %}
    <div class="pull-left" style="width:210px">
        {{ form.pic }}
    </div>

    <div class="col-xs-8">
        {% for field in form %}
            {% if not field.name == "pic" %}
                <div class="form-group {% if field.errors %}error{% endif %} {% if field.is_hidden %}hide{% endif %}">
                    <label for="id_{{ field.name }}" class="col-sm-2 col-xs-3 control-label">{{ field.label }}</label>
                    <div class="col-sm-6 col-xs-9">
                        {{ field }}
                    </div>
                    {% if field.errors %}
                        <div class="col-sm-4 col-xs-12">
                            {{ field.errors }}
                            <span class="help-block">{{ field.help_text }}</span>
                        </div>
                    {% endif %}
                </div>
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}

{% block inline_formset %}
    {% include 'product/includes/ingredient_inline_readonly.html' with object=object %}
    {% include 'product/includes/analysis_inline.html' with productanalysis_formset=productanalysis_formset %}
{% endblock %}

{% block header_page_script %}
    {{ block.super }}
    <script src="{% static 'js/jquery.formset.js' %}"></script>
{% endblock %}


{% block footer_base_script %}
    <script type="text/javascript" src="{% static 'adminlte/js/common-form.js' %}"></script>
    <script src="{% static 'js/jquery.formset.js' %}"></script>

    <script type="text/javascript">
        jQuery(document).ready(function ($) {
            $('#commonForm input').addClass('form-control');
            $('#commonForm select').addClass('form-control');
            $('#commonForm textarea').addClass('form-control');

            $("select[class$='form-control']").not("#{{ productanalysis_formset.prefix }}_table select").chosen({
                search_contains: true,
                disable_search_threshold: 10
            });
        });
    </script>
{% endblock %}

{% block footer_page_script %}
    <script>
        var productEditPageVue = new CommonFormPageVue({
            data: {
                list_api_tag: 'api:product-list',
                delete_api_tag: 'api:product-delete',
                detail_api_tag: 'api:product-detail',

                create_url_tag: 'product:product-add',
                list_url_tag: 'product:product-list',
                detail_url_tag: 'product:product-detail',
                update_url_tag: 'product:product-update'
            }
        });
    </script>
{% endblock %}

apps/product/templates/product/product_import.html
{% extends "adminlte/common_form.html" %}
{% load static adminlte_tags %}

{% block content_title %}导入产品{% endblock %}

{% block form_content %}
    <div class="col-xs-12">
        {{ form }}
    </div>
{% endblock %}

{% block form_footer %}
    <button type="submit" style="width:108px" class="btn btn-primary">提交</button>
{% endblock %}

apps/product/templates/product/product_list.html
{% extends "adminlte/common_list.html" %}
{% load static %}

{% block table_head %}
    <th class="text-center" style="width:65px;">
        <input type="checkbox" name="checkboxAllRow" class="checkboxAllRow" v-on:click="toggleAllBox"/>
    </th>
    <th></th>
    <th>品牌</th>
    <th>名称</th>
    <th>别名</th>
    <th>类别</th>
    <th></th>
{% endblock %}

{% block table_row %}
    <tbody v-for="item in items">
    <tr>
        <td class="text-center">
            ##[$index+1]
            <input type="checkbox" class="minimal" name="checkboxRow" value="#[item.id]"/>
        </td>
        <td>{!! item.brand_display !!}</td>
        <td>
            <a v-if="item.thumbnail" href="{!! item.edit_url !!}?from_page={!! currentPage !!}&search={!! search_keyword !!}"><img style="height:60px"
                                                                       src="{!! item.thumbnail !!}"/></a>
            <a v-else href="{!! item.edit_url !!}?from_page={!! currentPage !!}&search={!! search_keyword !!}"><img style="height:60px" src="/static/img/no_image.jpg"/></a>
        </td>
        <td>
            <a href="{!! item.edit_url !!}?from_page={!! currentPage !!}&search={!! search_keyword !!}">{!! item.name_cn !!}</a><br/>{!! item.name_en !!}
        </td>
        <td class="visible-sm visible-xs"><a href="{!! item.edit_url !!}?from_page={!! currentPage !!}&search={!! search_keyword !!}">{!! item.brand_display !!} {!! item.name_cn
            !!}</a>
        </td>
        <td>{!! item.alias !!}</td>
        <td>{!! item.category !!}</td>
        <td class="text-right hidden-sm hidden-xs">
            <template v-if="detail_url_tag">
                <a data-toggle="tooltip" data-placement="bottom" data-original-title="View"
                   href="#[item.detail_url]" class="btn btn-info btn-sm detail-btn" data-pk="#[item.id]">
                    <i class="fa fa-lg fa-bars fa-inverse"></i>
                </a>
            </template>

            <template v-if="update_url_tag">
                <a data-toggle="tooltip" data-placement="bottom" data-original-title="Edit"
                   href="#[item.edit_url]?from_page={!! currentPage !!}&search={!! search_keyword !!}" class="btn btn-warning btn-sm edit-btn" data-pk="#[item.id]">
                    <i class="fa fa-lg fa-pencil fa-inverse"></i>
                </a>
            </template>

            <template v-if="delete_api_tag">
                <a data-toggle="tooltip" data-placement="bottom" data-original-title="Delete"
                   data-pk="#[item.id]" v-on:click="removeOne" href="javascript:void(0);"
                   class="btn btn-danger btn-sm delete-btn">
                    <i class="fa fa-lg fa-trash-o fa-inverse"></i>
                </a>
            </template>
        </td>
    </tr>
    </tbody>
{% endblock %}

{% block common_list_footer_page_script %}
    <script type="text/javascript" src="{% static 'js/product/product_list.min.js' %}"></script>
{% endblock %}