apps/brand/api/urls.py
from django.conf.urls import url
from core.api.routers import PostHackedRouter
from . import views

router = PostHackedRouter()
router.include_root_view = False

# reverse('api:brand-list'), reverse('api:brand-detail', kwargs={'pk': 1})
router.register(r'brand', views.BrandViewSet, base_name='brand')

urlpatterns = [
    url(r'^brand/autocomplete/$', views.BrandAutocompleteAPIView.as_view(), name='brand-autocomplete'),
    url(r'^brand/search/$', views.BrandSearchAPIView.as_view(), name='brand-search'),
]

urlpatterns += router.urls

apps/brand/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views

# urls for brand
urlpatterns = [
    url(r'^brand/add/$', login_required(views.BrandAddView.as_view()), name='brand-add'),
    url(r'^brand/list/$', login_required(views.BrandListView.as_view()), name='brand-list'),
    url(r'^brand/(?P<pk>\d+)/$', views.BrandDetailView.as_view(), name='brand-detail'),
    url(r'^brand/(?P<pk>\d+)/edit/$', login_required(views.BrandUpdateView.as_view()), name='brand-update'),
]

apps/premium_product/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^premium_product/add/$', views.PremiumProductAddView.as_view(), name="premiumproduct-add"),
    url(r'^premium_product/$', views.PremiumProductListView.as_view(), name="premiumproduct-list"),
    url(r'^premium_product/(?P<pk>\d+)/$', views.PremiumProductDetailView.as_view(), name="premiumproduct-detail"),
    url(r'^premium_product/(?P<pk>\d+)/edit/$', views.PremiumProductUpdateView.as_view(), name="premiumproduct-update"),
    url(r'^premium_product/import/$', views.PremiumProductImportView.as_view(), name="premiumproduct-import"),
]

apps/product/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^product/add/$', views.ProductAddView.as_view(), name="product-add"),
    url(r'^product/$', views.ProductListView.as_view(), name="product-list"),
    url(r'^product/(?P<pk>\d+)/$', views.ProductDetailView.as_view(), name="product-detail"),
    url(r'^product/(?P<pk>\d+)/edit/$', views.ProductUpdateView.as_view(), name="product-update"),
    url(r'^product/import/$', views.ProductImportView.as_view(), name="product-import"),
]

config/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.views import serve

# from wagtail.wagtailadmin import urls as wagtailadmin_urls
# from wagtail.wagtailcore import urls as wagtail_urls
# from wagtail.wagtaildocs import urls as wagtaildocs_urls
# from wagtail.wagtailimages import urls as wagtailimages_urls
# from apps.wagtail.search.views import search as wagtail_search

from core.auth_user.views import ChangePasswordView
from core import auth_user
from core.auth_user.forms import CustomPasswordResetForm, CustomSetPasswordForm


def if_installed(appname, *args, **kwargs):
    ret = url(*args, **kwargs)
    if appname not in settings.INSTALLED_APPS:
        ret.resolve = lambda *args: None
    return ret


wagtail_urlpatterns = [
    # url(r'^admin/', include(wagtailadmin_urls)),
    # url(r'^documents/', include(wagtaildocs_urls)),
    # url(r'^images/', include(wagtailimages_urls)),
    # url(r'^search/$', wagtail_search, name='wagtail_search'),
    # url(r'^pages/', include(wagtail_urls)),
]

apps_urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('apps.dashboard.urls', namespace='dashboard')),
    url(r'^', include('core.auth_user.urls', namespace='users')),
    url(r'^brand/', include('apps.brand.urls', namespace='brand')),
    url(r'^product/', include('apps.product.urls', namespace='product')),
    url(r'^premium_product/', include('apps.premium_product.urls', namespace='premium_product')),
    url(r'^analysis/', include('apps.analysis.urls', namespace='analysis')),
    url(r'^survey/', include('apps.survey.urls', namespace='survey')),
    url(r'^report/', include('apps.report.urls', namespace='report')),
    url(r'^wx/', include('apps.weixin.urls', namespace='weixin')),
]

# REST API
api_urlpatterns = [
    url(r'^wx/', include('apps.weixin.api.urls')),
    url(r'^brand/', include('apps.brand.api.urls')),
    url(r'^product/', include('apps.product.api.urls')),
    url(r'^premium_product/', include('apps.premium_product.api.urls')),
    url(r'^analysis/', include('apps.analysis.api.urls')),
    url(r'^survey/', include('apps.survey.api.urls')),
    url(r'^report/', include('apps.report.api.urls')),
]

urlpatterns = wagtail_urlpatterns + apps_urlpatterns + [
    # REST API
    url(r'^api/', include(api_urlpatterns, namespace='api')),

    # auth
    url('^auth/change-password/$', ChangePasswordView.as_view(), name='change_password'),
    url('^auth/change-password-done/$', auth_user.views.ChangePasswordDoneView.as_view(), name='password_change_done'),

    # password reset
    url(r'^password/reset/$', auth_views.password_reset, {'template_name': 'adminlte/password_reset_form.html',
                                                          'email_template_name': 'adminlte/password_reset_email.html',
                                                          'password_reset_form': CustomPasswordResetForm},
        name='password_reset'),
    url(r'^password/reset/done/$', auth_views.password_reset_done,
        {'template_name': 'adminlte/password_reset_done.html'},
        name='password_reset_done'),
    url(r'^password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', auth_views.password_reset_confirm,
        {'template_name': 'adminlte/password_reset_confirm.html',
         'set_password_form': CustomSetPasswordForm},
        name='password_reset_confirm'),
    url(r'^password/reset/complete/$', auth_views.password_reset_complete,
        {'template_name': 'adminlte/password_reset_complete.html'},
        name='password_reset_complete'),

    # dbsettings
    # url(r'^djadmin/settings/', include('dbsettings.urls')),

    # django-tinymce
    # url(r'^tinymce/', include('tinymce.urls')),

    url(r'^MP_verify_aVcytWJVmPok60D5\.txt$', serve, kwargs={'path': 'MP_verify_aVcytWJVmPok60D5.txt'}),

    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:
    # url(r'^home/', include(wagtail_urls)),
]

if settings.DEBUG:
    from rest_framework_swagger.views import get_swagger_view
    from django.conf.urls.static import static

    urlpatterns += [
        url(r'^api/docs/$', get_swagger_view(title='OZSales API'))
    ]

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/brand/models.py
# coding=utf-8
import logging
import os
from django.db import models
from django.utils.translation import ugettext_lazy as _
from pypinyin import Style, pinyin, lazy_pinyin
from stdimage import StdImageField
from stdimage.utils import UploadToClassNameDir
from taggit.managers import TaggableManager

from django_countries.fields import CountryField
from core.django.models import PinYinFieldModelMixin, ResizeUploadedImageModelMixin
from config.settings import BRAND_LOGO_PHOTO_FOLDER, MEDIA_URL, MEDIA_ROOT

log = logging.getLogger(__name__)


class Brand(ResizeUploadedImageModelMixin, PinYinFieldModelMixin, models.Model):
    """品牌，skin_brand"""
    country = CountryField(verbose_name=_('country'))
    name_en = models.CharField(_('英文名称'), max_length=128, blank=True)
    name_cn = models.CharField(_('中文名称'), max_length=128, blank=True)
    pinyin = models.CharField(_('pinyin'), max_length=512, blank=True)
    alias = models.CharField(_(u'别名'), max_length=255, blank=True)
    first_letter_en = models.CharField(_('英文首字母'), max_length=128, blank=True)
    first_letter_cn = models.CharField(_('拼音首字母'), max_length=128, blank=True)
    logo = StdImageField(upload_to=UploadToClassNameDir(), blank=True, null=True, verbose_name=_('Logo'),
                         variations={
                             'thumbnail': (400, 400, True)
                         })
    created_at = models.DateTimeField(u"创建时间", auto_now_add=True)

    pinyin_fields_conf = [
        ('name_cn', Style.NORMAL, True),
        ('alias', Style.NORMAL, True),
    ]

    class Meta:
        verbose_name_plural = _('Brands')
        verbose_name = _('Brand')
        unique_together = ("name_en", "name_cn")
        index_together = ("name_en", "name_cn")

    def __str__(self):
        return self.name_cn or self.name_en

    def save(self, *args, **kwargs):
        self.resize_image('logo')  # resize images when first uploaded

        if self.name_en:
            self.first_letter_en = self.name_en.upper()[:1]
        if self.name_cn and not self.first_letter_cn:
            self.first_letter_cn = ''.join(lazy_pinyin(self.name_cn)).upper()[:1]
        super(Brand, self).save(*args, **kwargs)

apps/brand/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from core.django.widgets import ThumbnailImageInput
from .models import Brand


class BrandAddForm(forms.ModelForm):
    logo = forms.ImageField(label=_("Logo"), required=False,
                            widget=ThumbnailImageInput({'width': '210px', 'size': 'thumbnail'}))

    class Meta:
        model = Brand
        fields = ['name_en', 'name_cn', 'logo']


class BrandUpdateForm(BrandAddForm):
    class Meta:
        model = Brand
        fields = ['logo', 'name_en', 'first_letter_en', 'name_cn', 'first_letter_cn', 'alias']


class BrandDetailForm(BrandAddForm):
    class Meta:
        model = Brand
        fields = ['name_en', 'name_cn', 'logo']

apps/brand/api/views.py
import logging

import sys
from django.db.models import Q
from dal import autocomplete
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework import permissions, filters

from core.api.filters import PinyinSearchFilter
from core.utils.string import include_non_asc
from core.django.autocomplete import HansSelect2ViewMixin
from core.api.views import CommonViewSet
from ..models import Brand
from . import serializers

log = logging.getLogger(__name__)


class BrandViewSet(CommonViewSet):
    """ API views for Brand """
    queryset = Brand.objects.all()
    serializer_class = serializers.BrandSerializer
    filter_fields = ['name_en', 'name_cn']
    search_fields = ['name_cn']
    pinyin_search_fields = ['name_en', 'pinyin']  # search only input are all ascii chars
    filter_backends = (DjangoFilterBackend,
                       PinyinSearchFilter,
                       filters.OrderingFilter)


class BrandAutocompleteAPIView(HansSelect2ViewMixin, autocomplete.Select2QuerySetView):
    model = Brand
    paginate_by = 20  # no pagination

    def get_queryset(self):
        qs = Brand.objects.all()

        if include_non_asc(self.q):
            qs = qs.filter(name_cn__icontains=self.q)
        else:
            # all ascii, number and letter
            key = self.q.lower()
            qs = qs.filter(
                Q(pinyin__icontains=key) | Q(name_en__icontains=key)| Q(name_cn__icontains=key))
        return qs

    def get_results(self, context):
        return [
            {
                'id': self.get_result_value(result),
                'text': self.get_result_label(result),
                # 'image': result.logo.url if result.logo else None,
            } for result in context['object_list']
        ]

class BrandSearchAPIView(BrandAutocompleteAPIView):
    paginate_by = sys.maxsize  # no pagination

apps/brand/views.py
from django.views.generic import ListView, CreateView, UpdateView
from braces.views import SuperuserRequiredMixin

from core.django.views import CommonContextMixin
from .models import Brand
from . import forms


class BrandListView(SuperuserRequiredMixin, CommonContextMixin, ListView):
    """ List views for Brand """
    model = Brand
    template_name_suffix = '_list'  # brand/brand_list.html

    def get_context_data(self, **kwargs):
        context = super(BrandListView, self).get_context_data(**kwargs)
        context['table_titles'] = ['中文名称', '英文名称', u'别名', u'普通产品', u'优选产品''']
        context['table_fields'] = ['name_cn', 'name_en', 'alias', 'product_count', 'premium_product_count', 'id']
        return context


class BrandAddView(SuperuserRequiredMixin, CommonContextMixin, CreateView):
    """ Add views for Brand """
    model = Brand
    form_class = forms.BrandAddForm
    template_name = 'brand/brand_form.html'


class BrandUpdateView(SuperuserRequiredMixin, CommonContextMixin, UpdateView):
    """ Update views for Brand """
    model = Brand
    form_class = forms.BrandUpdateForm
    template_name = 'brand/brand_form.html'


class BrandDetailView(SuperuserRequiredMixin, CommonContextMixin, UpdateView):
    """ Detail views for Brand """
    model = Brand
    form_class = forms.BrandDetailForm
    template_name = 'adminlte/common_detail.html'

apps/brand/templates/brand/_menu.html
{% load brand_tags %}

<li class="treeview active">
    <a href="{% url 'brand:brand-list' %}">
        <i class='fa fa-shopping-bag'></i>
        <b>品牌</b>

        <span class="pull-right-container">
            <small class="label pull-right bg-blue">{% brand_counter %}</small>
        </span>
    </a>
</li>

apps/brand/templates/brand/brand_form.html
{% extends "adminlte/common_form.html" %}
{% load static adminlte_tags %}

{% block form_content %}
    <div class="pull-left" style="width:210px">
        {{ form.logo }}
    </div>

    <div class="col-xs-8">
    {% for field in form %}
        {% if not field.name == "logo" %}
            <div class="form-group {% if field.errors %}error{% endif %} {% if field.is_hidden %}hide{% endif %}">
                <label for="id_{{ field.name }}" class="col-sm-2 col-xs-3 control-label">{{ field.label }}</label>
                <div class="col-sm-6 col-xs-9">
                    {{ field }}
                </div>
                {% if field.errors %}
                    <div class="col-sm-4 col-xs-12">
                        {{ field.errors }}
                        <span class="help-block">{{ field.help_text }}</span>
                    </div>
                {% endif %}
            </div>
        {% endif %}
    {% endfor %}
    </div>
{% endblock %}


{% block header_page_script %}
    {{ block.super }}
    <script src="{% static 'js/jquery.formset.js' %}"></script>
{% endblock %}

{% block footer_page_script %}
    <script>
        var brandEditPageVue = new CommonFormPageVue({
            data: {
                // API
                list_api_tag: 'api:brand-list',
                detail_api_tag: 'api:brand-detail',
                product_detail_api_tag: 'api:brand-detail',
                delete_api_tag: 'api:brand-delete',
                // page
                create_url_tag: 'brand:brand-add',
                list_url_tag: 'brand:brand-list',
                update_url_tag: 'brand:brand-update',
                detail_url_tag: 'brand:brand-detail',
                list_url: Urls['api:brand-list']()
            }
        });
    </script>
{% endblock %}

apps/brand/templates/brand/brand_list.html
{% extends "adminlte/common_list.html" %}
{% load static %}

{% block table_row %}
    <tbody v-for="item in items">
    <tr>
    <td class="text-center hidden-sm hidden-x">
        ##[$index+1]
        <input type="checkbox" class="minimal" name="checkboxRow" value="#[item.id]"/>
    </td>
    <td>{!! item.name_cn !!}</td>
    <td>{!! item.name_en !!}</td>
    <td>{!! item.alias !!}</td>
    <td>
        <a v-if="item.product_count" href="{% url 'product:product-list' %}?search={!! item.name_cn !!}"
           class="btn btn-sm btn-info">
            {!! item.product_count !!}</a>
        <button v-else type="button" class="btn btn-sm btn-info">{!! item.product_count !!}</button>
    </td>
    <td>
        <a v-if="item.premium_product_count"
           href="{% url 'premium_product:premiumproduct-list' %}?search={!! item.name_cn !!}"
           class="btn btn-sm btn-success">
            {!! item.premium_product_count !!}</a>
        <button v-else type="button" class="btn btn-sm btn-success">{!! item.premium_product_count !!}</button>
    </td>
    <td class="text-right hidden-sm hidden-xs">
        <template v-if="update_url_tag">
            <a data-toggle="tooltip" data-placement="bottom" data-original-title="Edit"
               href="#[item.edit_url]?from_page={!! currentPage !!}&search={!! search_keyword !!}" class="btn btn-warning btn-sm edit-btn" data-pk="#[item.id]">
                <i class="fa fa-lg fa-pencil fa-inverse"></i>
            </a>
        </template>
        <template v-if="delete_api_tag">
            <a data-toggle="tooltip" data-placement="bottom" data-original-title="Delete"
               data-pk="#[item.id]" v-on:click="removeOne" href="javascript:void(0);"
               class="btn btn-danger btn-sm delete-btn">
                <i class="fa fa-lg fa-trash-o fa-inverse"></i>
            </a>
        </template>
    </td>
{% endblock %}

{% block common_list_footer_page_script %}
    <script type="text/javascript" src="{% static 'js/brand/brand_list.min.js' %}"></script>
{% endblock %}